language: scala

scala:
  - 2.11.12

env:
  global:
    - CODECOV_TOKEN="6e9981d6-a934-4c57-ac1e-76973cf6b898"

script:
  - sbt clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)