version: '3.4'
services:
  cassandra:
    image: bitnami/cassandra
    ports:
      - "9042:9042"
      - "7199:7199"
      - "7000:7000"
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "y"
      SA_PASSWORD: "ThisIsAdminP@ssword123"
  redis:
    image: bitnami/redis
    ports:
      - "6379:6379"
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
